# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://patrickkabongo.github.io/
title: Patrick Cisuaka Kabongo
email: cracciska@gmail.com
author: Patrick Cisuaka Kabongo
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 Patrick Cisuaka Kabongo. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/PatrickClive
  - title: github
    url: https://github.com/patrickkabongo/patrickkabongo.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/patrick-cisuaka-kabongo-8ba491127/
